Components/HeaderViewComponent.cs
using BookStore.Data;
using BookStore.Models;
using BookStore.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BookStore.Components;

public class HeaderViewComponent : ViewComponent
{
    private StoreDbContext _context;
    private UserManager<User> _userManager;

    public HeaderViewComponent(StoreDbContext context, UserManager<User> userManager)
    {
        _context = context;
        _userManager = userManager;

    }
    public IViewComponentResult Invoke(string viewName = "")
    {
        HeaderViewModel model = new HeaderViewModel
        {
            SearchAspController = "Book",
            Categories = _context.Categories
        };
        if (User.Identity != null && User.Identity.IsAuthenticated)
        {
            var userId = _userManager.GetUserId((System.Security.Claims.ClaimsPrincipal)User);
            int itemCount = _context.Carts
                     .Include(cart => cart.CartItems)
                     .FirstOrDefault(cart => cart.UserId == userId)
                      ?.CartItems?.Count() ?? 0;
            model.SearchAspController = "Book";
            if (User.IsInRole("Admin") || User.IsInRole("StoreOwner"))
            {
                model.SearchAspController = "StoreOwner";
            }
            model.CartCount = itemCount;

        }


        if (!string.IsNullOrEmpty(viewName))
        {
            return View(viewName, model);
        }
        return View(model);
    }

}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Greenwich Bookstore</title>
    <meta name="keywords" content="HTML5 Template">
    <meta name="description" content="Greenwich Bookstore">
    <meta name="author" content="p-themes">
    <!-- Favicon -->
    <link rel="manifest" href="~/assets/images/icons/site.html">
    <link rel="shortcut icon" href="~/assets/images/icons/favicon-2.ico">
    <meta name="apple-mobile-web-app-title" content="Greenwich Bookstore">
    <meta name="application-name" content="Greenwich Bookstore">
    <meta name="msapplication-TileColor" content="#cc9966">
    <meta name="msapplication-config" content="~/assets/images/icons/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="~/assets/vendor/line-awesome/line-awesome/line-awesome/css/line-awesome.min.css">
    <!-- Plugins CSS File -->
    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/css/plugins/owl-carousel/owl.carousel.css">
    <link rel="stylesheet" href="~/assets/css/plugins/magnific-popup/magnific-popup.css">
    <!-- Main CSS File -->
    <link rel="stylesheet" href="~/assets/css/style.css">
    <link rel="stylesheet" href="~/assets/css/demos/demo-20.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>

<body>
    <div class="page-wrapper">



        <vc:header />







        <main class="main">@RenderBody()</main>












        <footer class="footer">
            <div class="footer-middle">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-6 col-lg-3">
                            <div class="widget widget-about">
                                <img src="~/assets/images/FPTLogo.png" class="footer-logo" alt="Footer Logo" width="105"
                                    height="25">
                                <p>We are always welcome you to buy books from us. Book is the gift of the God Trans The
                                    House. </p>

                                <div class="social-icons">
                                    <a href="" class="social-icon" target="_blank" title="Facebook"><i
                                            class="icon-facebook-f"></i></a>
                                    <a href="" class="social-icon" target="_blank" title="Twitter"><i
                                            class="icon-twitter"></i></a>
                                    <a href="" class="social-icon" target="_blank" title="Instagram"><i
                                            class="icon-instagram"></i></a>
                                    <a href="" class="social-icon" target="_blank" title="Youtube"><i
                                            class="icon-youtube"></i></a>
                                    <a href="" class="social-icon" target="_blank" title="Pinterest"><i
                                            class="icon-pinterest"></i></a>
                                </div><!-- End .soial-icons -->
                            </div><!-- End .widget about-widget -->
                        </div><!-- End .col-sm-6 col-lg-3 -->

                        <div class="col-sm-6 col-lg-3">
                            <div class="widget">
                                <h4 class="widget-title">Useful Links</h4><!-- End .widget-title -->

                                <ul class="widget-list">
                                    <li><a href="about.html">About Molla</a></li>
                                    <li><a href="">How to shop on Molla</a></li>
                                    <li><a href="">FAQ</a></li>
                                    <li><a href="contact.html">Contact us</a></li>
                                    <li><a href="login.html">Log in</a></li>
                                </ul><!-- End .widget-list -->
                            </div><!-- End .widget -->
                        </div><!-- End .col-sm-6 col-lg-3 -->

                        <div class="col-sm-6 col-lg-3">
                            <div class="widget">
                                <h4 class="widget-title">Customer Service</h4><!-- End .widget-title -->

                                <ul class="widget-list">
                                    <li><a href="">Payment Methods</a></li>
                                    <li><a href="">Money-back guarantee!</a></li>
                                    <li><a href="">Returns</a></li>
                                    <li><a href="">Shipping</a></li>
                                    <li><a href="">Terms and conditions</a></li>
                                    <li><a href="">Privacy Policy</a></li>
                                </ul><!-- End .widget-list -->
                            </div><!-- End .widget -->
                        </div><!-- End .col-sm-6 col-lg-3 -->

                        <div class="col-sm-6 col-lg-3">
                            <div class="widget">
                                <h4 class="widget-title">My Account</h4><!-- End .widget-title -->

                                <ul class="widget-list">
                                    <li><a href="">Sign In</a></li>
                                    <li><a href="cart.html">View Cart</a></li>
                                    <li><a href="">My Wishlist</a></li>
                                    <li><a href="">Track My Order</a></li>
                                    <li><a href="">Help</a></li>
                                </ul><!-- End .widget-list -->
                            </div><!-- End .widget -->
                        </div><!-- End .col-sm-6 col-lg-3 -->
                    </div><!-- End .row -->
                </div><!-- End .container -->
            </div><!-- End .footer-middle -->

            <div class="footer-bottom">
                <div class="container">
                    <p class="footer-copyright">Copyright © 2023 Greenwich BookStore. All Rights Reserved.</p>
                    <!-- End .footer-copyright -->
                    <figure class="footer-payments">
                        <img src="~/assets/images/payments.png" alt="Payment methods" width="272" height="20">
                    </figure><!-- End .footer-payments -->
                </div><!-- End .container -->
            </div><!-- End .footer-bottom -->
        </footer><!-- End .footer -->
    </div><!-- End .page-wrapper -->
    <button id="scroll-top" title="Back to Top"><i class="icon-arrow-up"></i></button>


    <vc:header view-name="Sidebar" />






    <!-- Plugins JS File -->
    <script src="~/assets/js/jquery.min.js"></script>
    <script src="~/assets/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/js/jquery.hoverIntent.min.js"></script>
    <script src="~/assets/js/jquery.waypoints.min.js"></script>
    <script src="~/assets/js/superfish.min.js"></script>
    <script src="~/assets/js/owl.carousel.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            if ('@TempData.ContainsKey("SweetAlert_Title")' === 'True' && '@TempData.ContainsKey("SweetAlert_Description")' === 'True' && '@TempData.ContainsKey("SweetAlert_State")' === 'True') {
                var title = '@TempData["SweetAlert_Title"]';
                var description = '@TempData["SweetAlert_Description"]';
                var state = '@TempData["SweetAlert_State"]';
                swal(title, description, state);
            }
        });
    </script>

    <!-- Main JS File -->
    <script src="~/assets/main.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>