Models/Cart.cs
using System.ComponentModel.DataAnnotations;

namespace BookStore.Models;

public class Cart
{
    public int Id { get; set; }
    public required string UserId { get; set; }

    public ICollection<CartItem>? CartItems { get; set; }
}

Controllers/BookController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using BookStore.Models;
using BookStore.Data;
using BookStore.Models.ViewModels;
using Microsoft.EntityFrameworkCore;

namespace BookStore.Controllers;

public class BookController : Controller
{
    private StoreDbContext _context;
    public int PageSize = 6;

    public BookController(StoreDbContext context)
    {
        this._context = context;
    }
    public ViewResult Index(int? categoryId, string? sortby, string? searchQuery, int bookPage = 1)
    {
        IQueryable<Book> booksQuery = _context.Books
        .Include(b => b.Category)
        .Where(b => categoryId == null || b.CategoryId == categoryId);

        if (!string.IsNullOrEmpty(searchQuery))
        {
            searchQuery = searchQuery.ToLower();

            booksQuery = booksQuery.Where(b => b.Title.ToLower().Contains(searchQuery));
        }

        booksQuery = sortby switch
        {
            "Name" => booksQuery.OrderBy(b => b.Title),
            "Year" => booksQuery.OrderBy(b => b.YearPublished),
            "Id" => booksQuery.OrderBy(b => b.Id),
            _ => booksQuery.OrderBy(b => b.Title),
        };


        return View(new BookListViewModel
        {
            Books = booksQuery
            .Skip((bookPage - 1) * PageSize)
            .Take(PageSize),
            PagingInfo = new PagingInfo
            {
                CurrentPage = bookPage,
                ItemsPerPage = PageSize,
                TotalItems = booksQuery.Count(),
            },
            CurrentCategoryId = categoryId,
            CurrentCategoryName = _context.Categories.Find(categoryId)?.CategoryName,
            Categories = _context.Categories.Include(c => c.Books),
            CurrentSortby = sortby,
            CurrentSearchQuery = searchQuery
        });
    }

    public async Task<IActionResult> Detail(int? bookId)
    {
        if (bookId == null)
        {
            return RedirectToAction("Index");
        }

        Book? book = await _context.Books
            .Include(b => b.Category)
            .FirstOrDefaultAsync(b => b.Id == bookId);

        if (book == null)
        {
            return NotFound();
        }

        return View(book);
    }
}

Controllers/CartController.cs
using System.Linq;
using BookStore.Data;
using BookStore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualBasic;

namespace BookStore.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly StoreDbContext _context;
        private readonly UserManager<User> _userManager;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public CartController(StoreDbContext context, UserManager<User> userManager, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;
            _userManager = userManager;
        }

        public ViewResult Index()
        {
            Cart cart = GetCart();

            return View(cart);
        }

        public IActionResult AddToCart(int bookID, int quantity)
        {
            var book = _context.Books.Find(bookID);
            if (book == null)
            {
                return NotFound();
            }

            Cart cart = GetCart();

            var cartItem = cart?.CartItems?.FirstOrDefault(item => item.BookId == bookID);

            if (cartItem == null)
            {
                cartItem = new CartItem
                {
                    Cart = cart!,
                    Book = book,
                    Quantity = quantity + 1
                };
                _context.CartItems.Add(cartItem);
            }
            else
            {
                cartItem.Quantity++;
                _context.CartItems.Update(cartItem);
            }

            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult ClearCart()
        {
            var cart = GetCart();
            if (cart != null)
            {
                _context.CartItems.RemoveRange(cart.CartItems);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public IActionResult RemoveFromCart(int cartItemId)
        {
            var cartItem = _context.CartItems.Find(cartItemId);
            if (cartItem != null)
            {
                _context.CartItems.Remove(cartItem);
                _context.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public IActionResult ReduceQuantity(int cartItemId)
        {
            var cartItem = _context.CartItems?.Find(cartItemId);

            if (cartItem != null)
            {
                if (cartItem?.Quantity > 1)
                {
                    cartItem.Quantity--;
                    _context.CartItems?.Update(cartItem);
                }
                else
                {
                    _context.CartItems?.Remove(cartItem);
                }
                _context.SaveChanges();
            }

            return RedirectToAction("Index"); ;
        }

        public IActionResult IncreaseQuantity(int cartItemId)
        {
            var cartItem = _context.CartItems?.Find(cartItemId);
            if (cartItem != null)
            {
                cartItem.Quantity++;
                _context.CartItems.Update(cartItem);
                _context.SaveChanges();
            }

            return RedirectToAction("Index");
        }



        private Cart GetCart()
        {
            var userId = GetUserId();

            Cart cart = _context.Carts
                .Include(c => c.CartItems)
                .ThenInclude(ci => ci.Book)
                .FirstOrDefault(c => c.UserId == userId);

            if (cart == null)
            {
                cart = new Cart
                {
                    UserId = userId,
                    CartItems = new List<CartItem>()
                };
                _context.Carts.Add(cart);
                _context.SaveChanges();
            }

            return cart;

        }
        private string GetUserId()
        {
            var principal = _httpContextAccessor?.HttpContext?.User;
            string userId = _userManager.GetUserId(principal);
            return userId;
        }
        private int GetTotal()
        {
            var cart = GetCart();
            if (cart != null)
            {
                return cart.CartItems.Sum(item => item.Quantity);
            }
            return 0;
        }
        public IActionResult ContinueShopping()
        {
            return View("/Views/Book/Index.cshtml");
        }
    }
}

Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using BookStore.Data;
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace BookStore.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly StoreDbContext _context;
        private readonly UserManager<User> _userManager;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public OrderController(StoreDbContext context, UserManager<User> userManager, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;
            _userManager = userManager;

        }
        public ViewResult Index()
        {
            Cart cart = GetCart();

            return View(cart);
        }

        public IActionResult CreateOrder()
        {
            Cart cart = GetCart();

            if (cart.CartItems.Count == 0)
            {
                return RedirectToAction("Index", "Cart");
            }

            var order = new Order
            {
                UserId = cart.UserId,
                OrderItems = cart.CartItems.Select(ci => new OrderItem
                {
                    Order = null,
                    Book = null,
                    BookId = ci.BookId,
                    Quantity = ci.Quantity
                }).ToList()
            };

            foreach (var orderItem in order.OrderItems)
            {
                orderItem.Order = order;
                orderItem.Book = _context.Books.Find(orderItem.BookId);
            }

            _context.Orders.Add(order);
            _context.SaveChanges();

            ClearCart();

            return RedirectToAction("OrderHistory");
        }

        // Thanh toán
        public IActionResult CheckOut()
        {
            var cart = GetCart();

            if (cart?.CartItems?.Count == 0)
            {
                return RedirectToAction("Index", "Cart");
            }


            MarkOrderAsPaid();

            return RedirectToAction("CheckOutComplete");
        }

        public IActionResult CheckOutComplete()
        {
            return View();
        }

        private void ClearCart()
        {
            Cart cart = GetCart();
            _context.CartItems.RemoveRange(cart.CartItems);
            _context.SaveChanges();
        }

        private void MarkOrderAsPaid()
        {
            Cart cart = GetCart();
            var order = _context.Orders.Include(o => o.OrderItems).FirstOrDefault(o => o.UserId == cart.UserId && o.OrderItems.Any());

            if (order != null)
            {
                order.OrderDate = DateTime.Now;
                _context.SaveChanges();
            }
        }

        private Cart GetCart()
        {
            var userId = GetUserId();

            Cart cart = _context.Carts
                .Include(c => c.CartItems)
                .ThenInclude(ci => ci.Book)
                .FirstOrDefault(c => c.UserId == userId);

            if (cart == null)
            {
                cart = new Cart
                {
                    UserId = userId,
                    CartItems = new List<CartItem>()
                };
                _context.Carts.Add(cart);
                _context.SaveChanges();
            }

            return cart;
        }
        private string GetUserId()
        {
            var principal = _httpContextAccessor?.HttpContext?.User;
            string userId = _userManager.GetUserId(principal);
            return userId;
        }
        private int GetTotal()
        {
            var cart = GetCart();
            if (cart != null)
            {
                return cart.CartItems.Sum(item => item.Quantity);
            }
            return 0;
        }
        public IActionResult OrderHistory()
        {
            var userId = GetUserId();
            var orders = _context.Orders
                .Include(o => o.OrderItems)
                .ThenInclude(oi => oi.Book)
                .Where(o => o.UserId == userId)
                .ToList();

            return View(orders);
        }
    }
}

Views/Cart/Index.cshtml
@model Cart
<div class="page-header text-center" style="background-image: url('assets/images/page-header-bg.jpg')">
	<div class="container">
		<h1 class="page-title">Shopping Cart<span>Shop</span></h1>
	</div><!-- End .container -->
</div><!-- End .page-header -->
<nav aria-label="breadcrumb" class="breadcrumb-nav">
	<div class="container">
		<ol class="breadcrumb">
			<li class="breadcrumb-item"><a href="index.html">Home</a></li>
			<li class="breadcrumb-item"><a href="#">Shop</a></li>
			<li class="breadcrumb-item active" aria-current="page">Shopping Cart</li>
		</ol>
	</div><!-- End .container -->
</nav><!-- End .breadcrumb-nav -->

<div class="page-content">
	<div class="cart">
		<div class="container">
			<div class="row">
				<div class="col-lg-9">
					<table class="table table-cart table-mobile">
						<thead>
							<tr>
								<th>Book</th>
								<th>Price</th>
								<th>Quantity</th>
								<th>Total</th>
								<th></th>
							</tr>
						</thead>
						@foreach (var item in Model?.CartItems!)
						{
							var Total = item.Book.Price * item.Quantity;


							<tbody>
								<tr>
									<td class="product-col">
										<div class="product">
											<figure class="product-media">
												<a href="#">
													<img style="width: 6rem; height: 6rem;"
														src="~/upload/images/@item.Book.ImageUrl" alt="Product image">
												</a>
											</figure>

											<h3 class="product-title">
												<a>@item.Book.Title</a>
											</h3><!-- End .product-title -->
										</div><!-- End .product -->
									</td>
									<td class="price-col">@item.Book.Price</td>
									<td class="quantity-col">
										<div class="cart-product-quantity">
											<a asp-controller="Cart" asp-action="ReduceQuantity"
												asp-route-cartItemId="@item.Id"><i class="bi bi-dash-circle-fill"></i></a>
											<span class="cart-count">@item.Quantity</span>
											<a asp-controller="Cart" asp-action="IncreaseQuantity"
												asp-route-cartItemId="@item.Id"><i class="bi bi-plus-circle-fill"></i></a>
										</div><!-- End .cart-product-quantity -->
									</td>
									<td class="total-col">@Total</td>
									<td class="remove-col"><a class="btn-remove" asp-controller="Cart"
											asp-action="RemoveFromCart" asp-route-cartItemId="@item.Id" role="button"><i
												class="icon-close"></i></a>
									</td>
									
								</tr>

							</tbody>
						}
					</table>

					<!-- End .table table-wishlist -->



					<!-- End .cart-bottom -->
				</div>

				<!-- End .col-lg-9 -->
				<aside class="col-lg-3">
					<div class="summary summary-cart">
						<h3 class="summary-title">Cart Total</h3><!-- End .summary-title -->

						<table class="table table-summary">
							<tbody>
								<tr class="summary-shipping">
									<td>Shipping:</td>
									<td>&nbsp;</td>
								</tr>

								<tr class="summary-shipping-row">
									<td>
										<div class="custom-control custom-radio">
											<input type="radio" id="free-shipping" name="shipping"
												class="custom-control-input">
											<label class="custom-control-label" for="free-shipping">Free
												Shipping</label>
										</div><!-- End .custom-control -->
									</td>
									<td>$0.00</td>
								</tr><!-- End .summary-shipping-row -->

								<tr class="summary-total">
									<td>Total:</td>
									<td>$@Model.CartItems.Sum(item => item.Quantity * item.Book.Price)</td>
								</tr><!-- End .summary-total -->
							</tbody>
						</table><!-- End .table table-summary -->

						<a asp-controller="Order" asp-action="Index"
							class="btn btn-outline-primary-2 btn-order btn-block">PROCEED TO
							CHECKOUT</a>
					</div><!-- End .summary -->

					<a asp-controller="Book" asp-action="Index"
						class="btn btn-outline-dark-2 btn-block mb-3"><span>CONTINUE
							SHOPPING</span><i class="icon-refresh"></i></a>

				</aside>

				<!-- End .col-lg-3 -->
			</div>

			<!-- End .row -->
		</div>

		<!-- End .container -->
	</div>

	<!-- End .cart -->
</div>

<!-- End .page-content -->