Models/Book.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BookStore.Models;

public class Book
{
    public int Id { get; set; }

    [MaxLength(100)]
    public required string Title { get; set; }

    [MaxLength(300)]
    public string? ShortReview { get; set; }

    public string? Description { get; set; }

    [DataType(DataType.Currency), Column(TypeName = "decimal(18,2)"), DisplayFormat(DataFormatString = "{0:C}")]
    [Range(0, double.MaxValue, ErrorMessage = "Price must be a non-negative value.")]
    public required decimal Price { get; set; }


    [Display(Name = "Image")]
    [NotMapped]
    public IFormFile? ImageFile { get; set; }

    public string? ImageUrl { get; set; }

    public int CategoryId { get; set; }

    public Category? Category { get; set; }


    [Display(Name = "Author Name")]
    public required string Author { get; set; }

    [Range(0, 100), Display(Name = "Discount Percentage")]
    public int DiscountPercentage { get; set; } = 0;

    [DataType(DataType.Date), Display(Name = "Year Published")]
    [DisplayFormat(DataFormatString = "{0:yyyy}", ApplyFormatInEditMode = true)]
    public required string YearPublished { get; set; }

    [Display(Name = "Final Price")]
    [DisplayFormat(DataFormatString = "{0:C}")]
    public decimal FinalPrice => Price - Price * DiscountPercentage / 100;


}

Controllers/BookController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using BookStore.Models;
using BookStore.Data;
using BookStore.Models.ViewModels;
using Microsoft.EntityFrameworkCore;

namespace BookStore.Controllers;

public class BookController : Controller
{
    private StoreDbContext _context;
    public int PageSize = 6;

    public BookController(StoreDbContext context)
    {
        this._context = context;
    }
    public ViewResult Index(int? categoryId, string? sortby, string? searchQuery, int bookPage = 1)
    {
        IQueryable<Book> booksQuery = _context.Books
        .Include(b => b.Category)
        .Where(b => categoryId == null || b.CategoryId == categoryId);

        if (!string.IsNullOrEmpty(searchQuery))
        {
            searchQuery = searchQuery.ToLower();

            booksQuery = booksQuery.Where(b => b.Title.ToLower().Contains(searchQuery));
        }

        booksQuery = sortby switch
        {
            "Name" => booksQuery.OrderBy(b => b.Title),
            "Year" => booksQuery.OrderBy(b => b.YearPublished),
            "Id" => booksQuery.OrderBy(b => b.Id),
            _ => booksQuery.OrderBy(b => b.Title),
        };


        return View(new BookListViewModel
        {
            Books = booksQuery
            .Skip((bookPage - 1) * PageSize)
            .Take(PageSize),
            PagingInfo = new PagingInfo
            {
                CurrentPage = bookPage,
                ItemsPerPage = PageSize,
                TotalItems = booksQuery.Count(),
            },
            CurrentCategoryId = categoryId,
            CurrentCategoryName = _context.Categories.Find(categoryId)?.CategoryName,
            Categories = _context.Categories.Include(c => c.Books),
            CurrentSortby = sortby,
            CurrentSearchQuery = searchQuery
        });
    }

    public async Task<IActionResult> Detail(int? bookId)
    {
        if (bookId == null)
        {
            return RedirectToAction("Index");
        }

        Book? book = await _context.Books
            .Include(b => b.Category)
            .FirstOrDefaultAsync(b => b.Id == bookId);

        if (book == null)
        {
            return NotFound();
        }

        return View(book);
    }
}

Controllers/CartController.cs
using System.Linq;
using BookStore.Data;
using BookStore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualBasic;

namespace BookStore.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly StoreDbContext _context;
        private readonly UserManager<User> _userManager;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public CartController(StoreDbContext context, UserManager<User> userManager, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;
            _userManager = userManager;
        }

        public ViewResult Index()
        {
            Cart cart = GetCart();

            return View(cart);
        }

        public IActionResult AddToCart(int bookID, int quantity)
        {
            var book = _context.Books.Find(bookID);
            if (book == null)
            {
                return NotFound();
            }

            Cart cart = GetCart();

            var cartItem = cart?.CartItems?.FirstOrDefault(item => item.BookId == bookID);

            if (cartItem == null)
            {
                cartItem = new CartItem
                {
                    Cart = cart!,
                    Book = book,
                    Quantity = quantity + 1
                };
                _context.CartItems.Add(cartItem);
            }
            else
            {
                cartItem.Quantity++;
                _context.CartItems.Update(cartItem);
            }

            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult ClearCart()
        {
            var cart = GetCart();
            if (cart != null)
            {
                _context.CartItems.RemoveRange(cart.CartItems);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public IActionResult RemoveFromCart(int cartItemId)
        {
            var cartItem = _context.CartItems.Find(cartItemId);
            if (cartItem != null)
            {
                _context.CartItems.Remove(cartItem);
                _context.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public IActionResult ReduceQuantity(int cartItemId)
        {
            var cartItem = _context.CartItems?.Find(cartItemId);

            if (cartItem != null)
            {
                if (cartItem?.Quantity > 1)
                {
                    cartItem.Quantity--;
                    _context.CartItems?.Update(cartItem);
                }
                else
                {
                    _context.CartItems?.Remove(cartItem);
                }
                _context.SaveChanges();
            }

            return RedirectToAction("Index"); ;
        }

        public IActionResult IncreaseQuantity(int cartItemId)
        {
            var cartItem = _context.CartItems?.Find(cartItemId);
            if (cartItem != null)
            {
                cartItem.Quantity++;
                _context.CartItems.Update(cartItem);
                _context.SaveChanges();
            }

            return RedirectToAction("Index");
        }



        private Cart GetCart()
        {
            var userId = GetUserId();

            Cart cart = _context.Carts
                .Include(c => c.CartItems)
                .ThenInclude(ci => ci.Book)
                .FirstOrDefault(c => c.UserId == userId);

            if (cart == null)
            {
                cart = new Cart
                {
                    UserId = userId,
                    CartItems = new List<CartItem>()
                };
                _context.Carts.Add(cart);
                _context.SaveChanges();
            }

            return cart;

        }
        private string GetUserId()
        {
            var principal = _httpContextAccessor?.HttpContext?.User;
            string userId = _userManager.GetUserId(principal);
            return userId;
        }
        private int GetTotal()
        {
            var cart = GetCart();
            if (cart != null)
            {
                return cart.CartItems.Sum(item => item.Quantity);
            }
            return 0;
        }
        public IActionResult ContinueShopping()
        {
            return View("/Views/Book/Index.cshtml");
        }
    }
}

Views/Book/Detail.cshtml
@model Book

<nav aria-label="breadcrumb" class="breadcrumb-nav border-0 mb-0">
    <div class="container d-flex align-items-center">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Book</a></li>
            <li class="breadcrumb-item active" aria-current="page">Details</li>
        </ol>
    </div><!-- End .container -->
</nav><!-- End .breadcrumb-nav -->

<div class="page-content">
    <div class="container">
        <div class="product-details-top">
            <div class="row">
                <div class="col-md-6">
                    <div class="product-gallery product-gallery-vertical">
                        <div class="product-main-image">
                            <img style="width: 40rem; height: 40rem;" id="product-zoom"
                                src="~/upload/images/@Model.ImageUrl"
                                data-zoom-image="~/assets/images/products/single/1-big.jpg" alt="product image">
                        </div><!-- End .product-main-image -->

                    </div><!-- End .product-gallery -->
                </div><!-- End .col-md-6 -->
                <div class="col-md-6">
                    <div class="product-details">
                        <h1 class="product-title">@Model.Title</h1>
                        <!-- End .product-title -->
                        <div class="product-price">
                            $@Model.Price
                        </div><!-- End .product-price -->

                        <div class="product-content">
                            <p>@Model.ShortReview
                            </p>
                        </div><!-- End .product-content -->


                        <div class="details-filter-row details-row-size">
                            <btn class="btn btn-link pl-0" style="color: #ef837b;">Author: </btn>
                            <btn class="btn btn-outline-dark btn-round">
                                <i class="bi bi-people-fill"> @Model?.Author </i>
                            </btn>
                        </div><!-- End .details-filter-row -->
                        <div class="details-filter-row details-row-size">
                            <btn class="btn btn-link pl-0" style="color: #ef837b;">Category: </btn>
                            <btn class="btn btn-outline-dark btn-round"> <i class="bi bi-tag-fill">
                                    @Model?.Category?.CategoryName </i>
                            </btn>
                        </div><!-- End .details-filter-row -->
                        <div class="details-filter-row details-row-size">
                            <btn class="btn btn-link pl-0" style="color: #ef837b;">Published Year: </btn>
                            <btn class="btn btn-outline-dark btn-round">
                                <i class="bi bi-flag-fill"> @Model?.YearPublished </i>
                            </btn>
                        </div><!-- End .details-filter-row -->
                        <div class="product-details-action d-flex justify-content-center">
                            <a asp-asp-controller="Cart" asp-action="AddToCart" asp-route-bookID="@Model?.Id"
                                class="btn-product btn-cart"><span>add to cart</span></a>
                        </div><!-- End .product-details-action -->

                        <div class="product-details-footer">
                            <div class="social-icons social-icons-sm mx-auto">
                                <span class="social-label">Share:</span>
                                <a class="social-icon" title="Facebook" target="_blank"><i
                                        class="icon-facebook-f"></i></a>
                                <a class="social-icon" title="Twitter" target="_blank"><i class="icon-twitter"></i></a>
                                <a class="social-icon" title="Instagram" target="_blank"><i
                                        class="icon-instagram"></i></a>
                                <a class="social-icon" title="Pinterest" target="_blank"><i
                                        class="icon-pinterest"></i></a>
                            </div>
                        </div><!-- End .product-details-footer -->
                    </div><!-- End .product-details -->
                </div><!-- End .col-md-6 -->
            </div><!-- End .row -->
        </div><!-- End .product-details-top -->
        <div class="product-details-tab">
            <ul class="nav nav-pills justify-content-center" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="product-desc-link" data-toggle="tab" href="#product-desc-tab"
                        role="tab" aria-controls="product-desc-tab" aria-selected="true">Description</a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane fade show active" id="product-desc-tab" role="tabpanel"
                    aria-labelledby="product-desc-link">
                    <div class="product-desc-content">
                        <p>@Model?.Description</p>
                    </div><!-- End .product-desc-content -->
                </div><!-- .End .tab-pane -->
            </div><!-- End .tab-content -->
        </div><!-- End .product-details-tab -->

    </div><!-- End .container -->
</div><!-- End .page-content -->

Views/Book/Index.cshtml
@model BookListViewModel

<div class="page-header text-center" style="background-image: url('assets/images/page-header-bg.jpg')">
    <div class="container">
        @if (@Model?.CurrentCategoryName != null)
        {
            <h1 class="page-title">@Model?.CurrentCategoryName<span>Books</span></h1>
        }
        else
        {
            <h1 class="page-title">All<span>Books</span></h1>
        }
        @if (@Model?.CurrentSearchQuery != null)
        {
            <p class="page-title h5 mt-3 text-info">You searched "@Model?.CurrentSearchQuery"</p>
        }
    </div><!-- End .container -->
</div><!-- End .page-header -->
<nav aria-label="breadcrumb" class="breadcrumb-nav mb-2">
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Shop</a></li>
            <li class="breadcrumb-item active" aria-current="page">List</li>
        </ol>
    </div><!-- End .container -->
</nav><!-- End .breadcrumb-nav -->

<div class="page-content">
    <div class="container">
        <div class="row">
            <div class="col-lg-9">
                <div class="toolbox">
                    <div class="toolbox-left">
                        <div class="toolbox-info">
                            Showing <span>@Model?.Books.Count() of @Model?.PagingInfo?.TotalItems</span>
                            Books
                        </div><!-- End .toolbox-info -->
                    </div><!-- End .toolbox-left -->

                    <div class="toolbox-right">
                        <div class="toolbox-sort">
                            <label for="sortby">Sort by:</label>
                            <div class="select-custom">
                                <form name="sortby-form" asp-controller="Book" asp-action="Index"
                                    asp-route-categoryId="@Model?.CurrentCategoryId"
                                    asp-route-bookPage="@Model?.PagingInfo?.CurrentPage"
                                    asp-route-sortby="@Model?.CurrentSortby"
                                    asp-route-searchQuery="@Model?.CurrentSearchQuery">
                                    <select name="sortby" id="sortby" class="form-control">
                                        <option value="Name" selected="@(Model?.CurrentSortby == "Name")">Name</option>
                                        <option value="Year" selected="@(Model?.CurrentSortby == "Year")">Year</option>
                                        <option value="Id" selected="@(Model?.CurrentSortby == "Id")">Id</option>
                                    </select>
                                </form>
                            </div>
                        </div><!-- End .toolbox-sort -->

                    </div><!-- End .toolbox-right -->
                </div><!-- End .toolbox -->
                @foreach (var b in Model?.Books ?? Enumerable.Empty<Book>())
                {
                    <div class="products mb-3">
                        <div class="product product-list">
                            <div class="row">
                                <div class="col-6 col-lg-3">
                                    <figure class="product-media">
                                        <span class="product-label label-new">New</span>
                                        <a asp-controller="Book" asp-action="Detail" asp-route-bookId="@b.Id">
                                            <img src="~/upload/images/@b.ImageUrl" alt="Product image"
                                                class="product-image image-fluid">
                                        </a>
                                    </figure><!-- End .product-media -->
                                </div><!-- End .col-sm-6 col-lg-3 -->

                                <div class="col-6 col-lg-3 order-lg-last">
                                    <div class="product-list-action">
                                        <div class="product-price font-weight-bold justify-content-center">
                                            $@b.FinalPrice
                                        </div><!-- End .product-price -->

                                        <div class="product-action justify-content-center">
                                            <p class="btn-product btn-quickview" title="Quick view">
                                                <span class="text-nowrap" style="font-size: 1.4rem;">Published
                                                    <b>@b.YearPublished</b></span>
                                            </p>
                                        </div><!-- End .product-action -->

                                        <a asp-controller="Cart" asp-action="AddToCart" asp-route-bookID="@b.Id"
                                            class="btn-product btn-cart"><span>add to cart</span></a>
                                    </div><!-- End .product-list-action -->
                                </div><!-- End .col-sm-6 col-lg-3 -->

                                <div class="col-lg-6">
                                    <div class="product-body product-action-inner">
                                        <h3 class="product-title text-danger mb-1" style="font-size: large;"><a
                                                asp-controller="Book" asp-action="Detail"
                                                asp-route-bookId="@b.Id">@b.Title</a></h3>
                                        <!-- End .product-title -->
                                        <!-- End .product-cat -->
                                        <div class="product-cat mb-1" style="color: #ef837b;">
                                            <a href=""><i class="bi bi-tag-fill"> Category: </i>
                                                @b.Category?.CategoryName</a>
                                        </div>

                                        <a href="" class="product-author mb-1">
                                            <i class="bi bi-people-fill"> Author: @b.Author</i>
                                        </a>
                                        <div class="product-content mb-0">
                                            <p class="mb-1">@b.ShortReview</p>
                                        </div><!-- End .product-content -->
                                    </div><!-- End .product-body -->
                                </div><!-- End .col-lg-6 -->
                            </div><!-- End .row -->
                        </div><!-- End .product -->

                    </div>
                }
                <!-- End .products -->


                <!--Pagination link-->
                <nav aria-label="Page navigation" page-model="@Model?.PagingInfo" page-action="Index"
                    page-url-sortby="@Model?.CurrentSortby!" page-url-categoryId="@Model?.CurrentCategoryId!"
                    page-url-searchQuery="@Model?.CurrentSearchQuery!"></nav>
            </div><!-- End .col-lg-9 -->


            <aside class="col-lg-3 order-lg-first">
                <div class="sidebar sidebar-shop">
                    <div class="widget widget-clean">
                        <label>Filters:</label>
                        <a asp-controller="Book" asp-action="Index" class="sidebar-filter-clear">Clean All</a>
                    </div><!-- End .widget widget-clean -->

                    <div class="widget widget-collapsible">
                        <h3 class="widget-title">
                            <a data-toggle="collapse" href="#widget-1" role="button" aria-expanded="true"
                                aria-controls="widget-1">
                                Category
                            </a>
                        </h3><!-- End .widget-title -->

                        <div class="collapse show" id="widget-1">
                            <div class="widget-body">
                                <div class="filter-items filter-items-count">
                                    @foreach (Category c in Model?.Categories ?? Enumerable.Empty<Category>())
                                    {
                                        <div class="filter-item">
                                            <div class="custom-control custom-checkbox">
                                                <form asp-controller="Book" asp-action="Index" asp-route-categoryId="@c.Id"
                                                    asp-route-sortby="@Model?.CurrentSortby"
                                                    asp-route-searchQuery="@Model?.CurrentSearchQuery">
                                                    <input @(c.Id == Model?.CurrentCategoryId ? "checked" : "")
                                                        type="checkbox" class="custom-control-input" id="cat-@c.Id"
                                                        data-auto-submit>
                                                    <label class="custom-control-label"
                                                        for="cat-@c.Id">@c.CategoryName</label>
                                                </form>
                                            </div><!-- End .custom-checkbox -->
                                            <span class="item-count">@c.Books?.Count()</span>
                                        </div>
                                    }
                                </div><!-- End .filter-items -->
                            </div><!-- End .widget-body -->
                        </div><!-- End .collapse -->
                    </div><!-- End .widget -->



                </div><!-- End .sidebar sidebar-shop -->
            </aside><!-- End .col-lg-3 -->
        </div><!-- End .row -->
    </div><!-- End .container -->
</div><!-- End .page-content -->