Models/CategoryRequest.cs
using System.ComponentModel.DataAnnotations;

namespace BookStore.Models;

public class CategoryRequest
{
    public int Id { get; set; }

    public required string CategoryName { get; set; }

    public required string Description { get; set; }

    public DateTime RequestDate { get; set; } = DateTime.Now;


    public string? StoreOwnerId { get; set; }


    public string Status { get; set; } = "Pending";

}

Models/ViewModels/BookEditorViewModel.cs
namespace BookStore.Models.ViewModels;

public class BookEditorViewModel
{

    public string Action { get; set; } = "Create";

    public string FormName { get; set; } = "Add Book";
    public Book? Book { get; set; }

    public IEnumerable<Category> Categories { get; set; } = Enumerable.Empty<Category>();



}

Controllers/StoreOwnerController.cs
/* The above code is a C# controller class for managing the bookstore application. It includes various
actions for handling book management, category requests, and order management. */
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using BookStore.Models;
using BookStore.Data;
using BookStore.Models.ViewModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;
using SixLabors.ImageSharp.Formats.Jpeg;
using SixLabors.ImageSharp.Formats;
using SixLabors.ImageSharp.Formats.Png;
using SixLabors.ImageSharp.Formats.Webp;

namespace BookStore.Controllers;

[Authorize(Roles = "StoreOwner,Admin")]
public class StoreOwnerController : Controller
{
    private StoreDbContext _context;
    private readonly UserManager<User> _userManager;
    public int PageSize = 6;

    public StoreOwnerController(StoreDbContext context, UserManager<User> userManager)
    {
        _context = context;
        _userManager = userManager;
    }
    public ViewResult Index(int? categoryId, string? sortby, string? searchQuery, int bookPage = 1)
    {
        IQueryable<Book> booksQuery = _context.Books
        .Include(b => b.Category)
        .Where(b => categoryId == null || b.CategoryId == categoryId);

        if (!string.IsNullOrEmpty(searchQuery))
        {
            searchQuery = searchQuery.ToLower();

            booksQuery = booksQuery.Where(b => b.Title.ToLower().Contains(searchQuery));
        }

        booksQuery = sortby switch
        {
            "Name" => booksQuery.OrderBy(b => b.Title),
            "Year" => booksQuery.OrderBy(b => b.YearPublished),
            "Id" => booksQuery.OrderBy(b => b.Id),
            _ => booksQuery.OrderBy(b => b.Title),
        };


        return View(new BookListViewModel
        {
            Books = booksQuery
            .Skip((bookPage - 1) * PageSize)
            .Take(PageSize),
            PagingInfo = new PagingInfo
            {
                CurrentPage = bookPage,
                ItemsPerPage = PageSize,
                TotalItems = booksQuery.Count(),
            },
            CurrentCategoryId = categoryId,
            CurrentCategoryName = _context.Categories.Find(categoryId)?.CategoryName,
            Categories = _context.Categories.Include(c => c.Books),
            CurrentSortby = sortby,
            CurrentSearchQuery = searchQuery
        });
    }


    [HttpGet]
    public ViewResult Create()
    {
        TempData["ReturnUrl"] = HttpContext.Request.Headers["Referer"].ToString();
        return View("BookEditor", new BookEditorViewModel
        {
            Categories = _context.Categories
        });
    }

    [HttpPost]
    public async Task<IActionResult> Create([FromForm] Book book)
    {
        if (ModelState.IsValid)
        {
            string? uploadedFileName = await UploadImageAsync(book.ImageFile);

            if (!string.IsNullOrEmpty(uploadedFileName))
            {
                book.ImageUrl = uploadedFileName;
            }

            _context.Books.Add(book);
            await _context.SaveChangesAsync();
            return RedirectWithReturnUrl("Goodjob!", "You added a book!", "success");
        }
        return View("BookEditor", ViewModelFactory.Create(book, _context.Categories));
    }

    [HttpGet]
    public async Task<IActionResult> Edit(int bookId)
    {
        Book? book = await _context.Books.FindAsync(bookId);

        if (book != null)
        {
            BookEditorViewModel model = ViewModelFactory.Edit(book, _context.Categories);
            TempData["ReturnUrl"] = HttpContext.Request.Headers["Referer"].ToString();
            return View("BookEditor", model);
        }
        return RedirectWithReturnUrl("Failed", "Cannot edit this book!", "error");
    }



    [HttpPost]
    public async Task<IActionResult> Edit([FromForm] Book book)
    {
        if (ModelState.IsValid)
        {
            string? uploadedFileName = await UploadImageAsync(book.ImageFile);
            if (!string.IsNullOrEmpty(uploadedFileName))
            {
                // Delete existing image
                if (!string.IsNullOrEmpty(book.ImageUrl))
                {
                    string oldImagePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\upload", "images", book.ImageUrl);
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }
                book.ImageUrl = uploadedFileName;
            }

            _context.Books.Update(book);
            await _context.SaveChangesAsync();
            return RedirectWithReturnUrl("Goodjob!", "You updated a book!", "success");
        }
        return View("BookEditor", ViewModelFactory.Edit(book, _context.Categories));
    }



    public async Task<IActionResult> Delete(int bookId)
    {
        Book? book = await _context.Books.FindAsync(bookId);
        if (book != null)
        {
            TempData["ReturnUrl"] = HttpContext.Request.Headers["Referer"].ToString();
            _context.Books.Remove(book);
            await _context.SaveChangesAsync();
            return RedirectWithReturnUrl("Goodjob!", "You deleted a book!", "success");
        }
        return RedirectWithReturnUrl("Failed!", "Cannot delete this book because error!", "error");
    }

    [HttpGet]
    [Authorize]
    public ViewResult CategoryRequest()
    {
        return View();
    }

    [HttpPost]
    [Authorize]
    public async Task<IActionResult> CategoryRequest([FromForm] CategoryRequest categoryRequest)
    {
        if (!ModelState.IsValid)
        {
            return View(categoryRequest);
        }
        string Name = categoryRequest.CategoryName;
        if (_context.Categories.Any(c => c.CategoryName == Name) || _context.CategoryRequests.Any(c => c.CategoryName == Name))
        {
            return RedirectWithReturnUrl("Failed!", "You request an existed category!", "error");
        }
        if (User.Identity != null && User.Identity.IsAuthenticated)
        {
            User? user = await _userManager.GetUserAsync(User);
            categoryRequest.StoreOwnerId = user?.Id;
            categoryRequest.Status = "Pending";
        }
        _context.CategoryRequests.Add(categoryRequest);
        await _context.SaveChangesAsync();
        return RedirectWithReturnUrl("Goodjob!", "You requested a new category", "success");

    }

    [HttpGet]
    public ViewResult OrderManage()
    {
        var orders = _context.Orders.Include(o => o.OrderItems)
                .ThenInclude(oi => oi.Book).ToList();


        return View(orders);
    }


    public IActionResult OrderApprove(int orderId, string status)
    {
        var order = _context.Orders.FirstOrDefault(o => o.Id == orderId);

        if (order != null)
        {
            order.Status = status;
            _context.SaveChanges();
        }

        return RedirectWithReturnUrl("Goodjob!", "You processed an order", "success");
    }




    private Task<string?> UploadImageAsync(IFormFile? imageFile)
    {
        if (imageFile != null && imageFile.Length > 0)
        {
            string uniqueFileName = Guid.NewGuid().ToString() + "_" + imageFile.FileName;
            string imagePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\upload", "images", uniqueFileName);

            using (var image = Image.Load(imageFile.OpenReadStream()))
            {
                int targetWidth = 200;
                int targetHeight = 200;
                image.Mutate(c => c.Resize(targetWidth, targetHeight));
                image.Save(imagePath);
                // Return the unique file name
                return Task.FromResult<string?>(uniqueFileName);
            }
        }
        return Task.FromResult<string?>(null);
    }




    private IActionResult RedirectWithReturnUrl(string title, string description, string state)
    {
        string? returnUrl = TempData["ReturnUrl"] as string;

        TempData.Remove("ReturnUrl");
        TempData["SweetAlert_Title"] = title;
        TempData["SweetAlert_Description"] = description;
        TempData["SweetAlert_State"] = state;
        if (!string.IsNullOrEmpty(returnUrl))
        {
            return Redirect(returnUrl);
        }
        return RedirectToAction("Index");
    }
}

Views/StoreOwner/BookEditor.cshtml
@model BookEditorViewModel
<div class="login-page bg-image pt-8 pb-8 pt-md-12 pb-md-12 pt-lg-17 pb-lg-17"
    style="background-image: url('/assets/images/backgrounds/login-bg.png')">
    <div class="container">
        <div class="form-box">
            <div class="form-tab">
                <ul class="nav nav-pills nav-fill" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" role="tab">@Model?.FormName</a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane fade show active" role="tabpanel">
                        <form asp-controller="StoreOwner" asp-action="@Model?.Action" method="POST"
                            enctype="multipart/form-data">
                            @if (Model?.Action == "Edit")
                            {
                                <div class="input-group input-group-lg mt-1 mb-2">
                                    <div class="input-group-prepend">
                                        <label asp-for="Book!.Id"
                                            class="input-group-text bg-primary text-white input-group-elements-lg"><i
                                                class="bi bi-bookmark-check"> Id</i></label>
                                    </div>
                                    <input asp-for="Book!.Id" class="form-control input-group-elements-lg " readonly>
                                </div>
                            }
                            <div class="input-group input-group-lg mt-1 mb-2">
                                <div class="input-group-prepend">
                                    <label asp-for="Book!.Title"
                                        class="input-group-text bg-primary text-white input-group-elements-lg"><i
                                            class="bi bi-bookmark-check"> Title</i></label>
                                </div>
                                <input asp-for="Book!.Title" type="text" class="form-control input-group-elements-lg "
                                    placeholder="Enter title" required>
                                <span asp-validation-for="Book!.Title" class="invalid-feedback custom-invalid-feedback">
                                </span>
                            </div>

                            <div class="input-group input-group-lg mt-1 mb-2">
                                <div class="input-group-prepend">
                                    <label asp-for="Book!.ShortReview"
                                        class="input-group-text bg-primary text-white input-group-elements-lg"><i
                                            class="bi bi-eye"> Short Review</i></label>
                                </div>
                                <input asp-for="Book!.ShortReview" type="text"
                                    class="form-control input-group-elements-lg " placeholder="Enter short review"
                                    required>
                                <span asp-validation-for="Book!.ShortReview"
                                    class="invalid-feedback custom-invalid-feedback">
                                </span>
                            </div>

                            <div class="input-group input-group-lg mt-1 mb-2">
                                <div class="input-group-prepend">
                                    <label asp-for="Book!.CategoryId"
                                        class="input-group-text bg-primary text-white input-group-elements-lg"><i
                                            class="bi bi-tags"> Category</i></label>
                                </div>
                                <select asp-for="Book!.CategoryId" class="custom-select input-group-elements-lg">
                                    @foreach (Category c in Model?.Categories ?? Enumerable.Empty<Category>())
                                    {
                                        <option value="@c.Id">@c.CategoryName</option>
                                    }
                                </select>
                                <span asp-validation-for="Book!.CategoryId"
                                    class="invalid-feedback custom-invalid-feedback">
                                </span>
                            </div>

                            <div class=" input-group input-group-lg mt-1 mb-2">
                                <div class="input-group-prepend">
                                    <label asp-for="Book!.Description"
                                        class="input-group-text bg-primary text-white input-group-elements-lg"><i
                                            class="bi bi-bookmark-check"> Description</i> </label>
                                </div>
                                <textarea asp-for="Book!.Description" type="text"
                                    class="form-control input-group-elements-lg" required></textarea>
                                <span asp-validation-for="Book!.Description"
                                    class="invalid-feedback custom-invalid-feedback">
                                </span>
                            </div>

                            <div class="input-group input-group-lg mt-1 mb-2">
                                <div class="input-group-prepend">
                                    <label asp-for="Book!.Price"
                                        class="input-group-text bg-primary text-white input-group-elements-lg"><i
                                            class="bi bi-coin"> Price</i></label>
                                </div>
                                <input asp-for="Book!.Price" type="number" class="form-control input-group-elements-lg"
                                    placeholder="Enter price" required>
                                <span asp-validation-for="Book!.Price" class="invalid-feedback custom-invalid-feedback">
                                </span>
                            </div>

                            <div class="input-group input-group-lg mt-1 mb-2">
                                <div class="input-group-prepend">
                                    <label asp-for="Book!.Author"
                                        class="input-group-text bg-primary text-white input-group-elements-lg"><i
                                            class="bi bi-person-fill"> Author</i></label>
                                </div>
                                <input asp-for="Book!.Author" type="text" class="form-control input-group-elements-lg"
                                    placeholder="Enter author name" required>
                                <span asp-validation-for="Book!.Author"
                                    class="invalid-feedback custom-invalid-feedback">
                                </span>
                            </div>

                            <div class="input-group input-group-lg mt-1 mb-2">
                                <div class="input-group-prepend">
                                    <label asp-for="Book!.YearPublished"
                                        class="input-group-text bg-primary text-white input-group-elements-lg"><i
                                            class="bi bi-calendar-check"> Published Year</i></label>
                                </div>
                                <input asp-for="Book!.YearPublished" type="number"
                                    class="form-control input-group-elements-lg" placeholder="Enter published year"
                                    required>
                                <span asp-validation-for="Book!.YearPublished"
                                    class="invalid-feedback custom-invalid-feedback">
                                </span>
                            </div>

                            <div class="input-group input-group-lg mt-1 mb-2">
                                <div class="input-group-prepend">
                                    <label asp-for="Book!.DiscountPercentage"
                                        class="input-group-text bg-primary text-white input-group-elements-lg"><i
                                            class="bi bi-percent"> Discount</i></label>
                                </div>
                                <input asp-for="Book!.DiscountPercentage" type="number" value="0"
                                    class="form-control input-group-elements-lg" placeholder="Enter % discount">
                                <span asp-validation-for="Book!.DiscountPercentage"
                                    class="invalid-feedback custom-invalid-feedback">
                                </span>
                            </div>

                            <div class="input-group input-group-lg mt-1 mb-2">
                                <div class="input-group-prepend">
                                    <label asp-for="Book!.ImageFile"
                                        class="input-group-text bg-primary text-white input-group-elements-lg"><i
                                            class="bi bi-image"> Image</i></label>
                                </div>
                                <input asp-for="Book!.ImageFile" type="file" accept=".jpg, .jpeg, .png, .webp"
                                    class="form-control input-group-elements-lg">
                                <span asp-validation-for="Book!.ImageFile"
                                    class="invalid-feedback custom-invalid-feedback">
                                </span>
                            </div>

                            <!-- End .form-group -->
                            <div class="form-footer row justify-content-end">
                                <button type="submit" class="btn btn-outline-info">
                                    <span>Submit</span>
                                </button>
                                <button aria-label="Close" class="btn btn-outline-danger">
                                    <span>Close</span>
                                </button>
                            </div>
                            <!-- End .form-footer -->
                        </form>
                    </div>
                    <!-- .End .tab-pane -->
                </div>
                <!-- End .tab-content -->
            </div>
            <!-- End .form-tab -->
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Views/StoreOwner/CategoryRequest.cshtml
@model CategoryRequest
<div class="login-page bg-image pt-8 pb-8 pt-md-12 pb-md-12 pt-lg-17 pb-lg-17"
    style="background-image: url('/assets/images/backgrounds/login-bg.png')">
    <div class="container">
        <div class="form-box">
            <div class="form-tab">
                <ul class="nav nav-pills nav-fill" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" role="tab">Request Category</a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane fade show active" role="tabpanel">
                        <form asp-controller="StoreOwner" asp-action="CategoryRequest" method="POST"
                            enctype="multipart/form-data">
                            <div class="input-group input-group-lg mt-1 mb-2">
                                <div class="input-group-prepend">
                                    <label asp-for="CategoryName"
                                        class="input-group-text bg-primary text-white input-group-elements-lg"><i
                                            class="bi bi-bookmark-check"> Category Name</i></label>
                                </div>
                                <input asp-for="CategoryName" type="text" class="form-control input-group-elements-lg "
                                    placeholder="Enter title" required>
                                <span asp-validation-for="CategoryName"
                                    class="invalid-feedback custom-invalid-feedback">
                                </span>
                            </div>



                            <div class=" input-group input-group-lg mt-1 mb-2">
                                <div class="input-group-prepend">
                                    <label asp-for="Description"
                                        class="input-group-text bg-primary text-white input-group-elements-lg"><i
                                            class="bi bi-bookmark-check"> Description</i> </label>
                                </div>
                                <textarea asp-for="Description" type="text" class="form-control input-group-elements-lg"
                                    required></textarea>
                                <span asp-validation-for="Description" class="invalid-feedback custom-invalid-feedback">
                                </span>
                            </div>

                            <!-- End .form-group -->
                            <div class="form-footer row justify-content-end">
                                <button type="submit" class="btn btn-outline-info">
                                    <span>Submit</span>
                                </button>
                                <button aria-label="Close" class="btn btn-outline-danger">
                                    <span>Close</span>
                                </button>
                            </div>
                            <!-- End .form-footer -->
                        </form>
                    </div>
                    <!-- .End .tab-pane -->
                </div>
                <!-- End .tab-content -->
            </div>
            <!-- End .form-tab -->
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Views/StoreOwner/OrderManage.cshtml
@model List<BookStore.Models.Order>

<div class="container-fluid py-5">
    <div class="text-center wow fadeInUp row justify-content-between" data-wow-delay="0.1s">
        <div class="col-md-3">
            <button class="btn btn-warning btn-lg rounded-pill">
                Welcome to OrderManage
                <i class="bi bi-chat-heart-fill text-white"></i>
            </button>
        </div>
        <div class="col-md-3">
            <h6 class="section-title bg-white text-center text-primary px-3">
                Orders
            </h6>
            <h1 class="mb-4">Order history</h1>
        </div>

        <div class="col-md-3">
            <button class="btn btn-info btn-lg rounded-pill">
                <i class="bi bi-box-seam-fill"></i>
                You have @Model.Count() orders
            </button>
        </div>

        <table class="table table-striped  mb-0 bg-white mt-3">
            <thead class="bg-light thead-dark text-center fs-5">
                <tr>
                    <th><i class="fa-solid fa-box"></i> Order Number</th>
                    <th><i class="fa-solid fa-calendar"></i> Created date</th>
                    <th><i class="fa-solid fa-calendar"></i> UserID</th>
                    <th><i class="fa-solid fa-money-check-dollar"></i> Total</th>
                    <th><i class="fa-solid fa-circle-info"></i> Status</th>
                    <th><i class="fa-sharp fa-solid fa-file-invoice"></i> Details</th>
                </tr>
            </thead>
            <tbody class="text-center">
                @if (Model != null && Model.Count > 0)
                {
                    var i = 0;
                    @foreach (var order in Model)
                    {
                        i++;
                        <tr>
                            <td>
                                <p class="fw-bold m-1"></p>
                                <p class="fw-bold m-1">@i</p>
                            </td>
                            <td>
                                <p class="fw-semi-bold m-1 fw-5">
                                    @order.OrderDate
                                </p>
                            </td>
                            <td>@order.UserId</td>
                            <td class="fw-semi-bold fs-4">@(order.OrderItems.Sum(oi => oi.Quantity * oi.Book.Price)) $
                            </td>
                            <td>
                                <span
                                    class="btn rounded-pill d-inline m-1 @(order.Status == "Accept" ? "btn-success" : order.Status == "Reject" ? "btn-danger" : "btn-secondary")">@order.Status</span>
                            </td>


                            <td>
                                <div class="d-flex flex-column">
                                    <button type="button" class="btn btn-info btn-rounded btn-sm fw-bold" data-toggle="modal"
                                        data-target="#orderdetail-@order.Id">
                                        View details
                                    </button>
                                    @if (@order.Status == "Pending")
                                    {
                                        <a role="button" asp-controller="StoreOwner" asp-action="OrderApprove"
                                            asp-route-orderId="@order.Id" asp-route-status="Accept" class="btn btn-success"
                                            style="background-color:rgb(29, 250, 0); border-color:rgb(0, 0, 0); color:rgb(0, 0, 0)">Accept
                                        </a>
                                        <a role="button" asp-controller="StoreOwner" asp-action="OrderApprove"
                                            asp-route-orderId="@order.Id" asp-route-status="Reject" class="btn btn-danger"
                                            style="background-color:rgb(247, 63, 63); border-color:rgb(0, 0, 0); color:rgb(0, 0, 0)">Reject
                                        </a>
                                    }
                                    else
                                    {
                                        <button class="btn btn-sm btn-secondary">This order has been rocessed</button>
                                    }
                                </div>
                            </td>
                        </tr>
                        <!-- The Modal -->
                        <div class="modal fade" id="orderdetail-@order.Id" tabindex="-1">
                            <div class="modal-dialog">
                                <div class="modal-content" style="background-color: #ebebeb;">
                                    <div class="modal-header border-bottom-0">
                                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                            aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body text-start text-black p-4">
                                        <h5 class="modal-title text-uppercase mb-5">
                                            Order detail #@i
                                        </h5>
                                        <h4 class="mb-5" style="color: #35558a">
                                            Thanks for your payment
                                        </h4>
                                        <p class="mb-0" style="color: #35558a">Payment summary</p>
                                        <hr class="mt-2 mb-4"
                                            style="height: 0; background-color: transparent; opacity: 0.75; border-top: 2px dashed #9e9e9e;" />
                                        @foreach (var item in order.OrderItems)
                                        {
                                            <div class="d-flex justify-content-between">
                                                <p class="fw-bold mb-0">@item.Book.Title </p>
                                                <p class="text-muted mb-0">$ @item.Book.Price</p>
                                            </div>
                                        }
                                        <div class="d-flex justify-content-between">
                                            <p class="small mb-0">Promotions</p>
                                            <p class="small mb-0">None</p>
                                        </div>
                                        <div class="d-flex justify-content-between pb-1">
                                            <p class="small">Tax</p>
                                            <p class="small">Included</p>
                                        </div>
                                        <div class="d-flex justify-content-between">
                                            <p class="fw-bold">Total</p>
                                            <p class="fw-bold" style="color: #35558a">$@(order.OrderItems.Sum(oi => oi.Quantity
                                        * oi.Book.Price))</p>
                                        </div>
                                    </div>
                                    <div class="modal-footer d-flex justify-content-center border-top-0 py-4">
                                        <button type="button" class="btn btn-primary btn-lg mb-1" data-dismiss="modal"
                                            style="background-color: #35558a">
                                            Close
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                }
            </tbody>
        </table>

    </div>
</div>